import { SWRConfig } from 'swr';
import Head from 'next/head';

import '@/src/styles/globals.css';
import Layout from '@/src/components/Layout';
import { fetcher } from '@/src/utils/fetcher';

import type { AppProps } from 'next/app';

const App = ({ Component, pageProps }: AppProps) => {
    return (
        <>
            <Head>
                <title>Index</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SWRConfig value={{ fetcher }}>
                <Layout>
                    <Component {...pageProps} />
                </Layout>
            </SWRConfig>
        </>
    );
};

export default App;
