import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { Footer } from '@/components/Footer'
import { NextJsLogo } from '@/components/NextJsLogo'
import { Description } from '@/components/Description'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Description page='about'/>

        <NextJsLogo/>

        <Footer/>
      </main>
    </>
  )
}
